# Generated by Django 5.2.1 on 2026-01-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_bud', '0004_budgetperiod_category_expense_expensesplit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='join_at',
            new_name='joined_at',
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
